const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Physics,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.PlatformInfo.Cnds.IsCordovaExport,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{BackgroundMenu: 0},
	{WhiteBoard: 0},
	{Sine: 0},
	{Tween: 0},
	{btnPlay: 0},
	{btnSettings: 0},
	{btnShop: 0},
	{Counters: 0},
	{GameLogo: 0},
	{MaxPt: 0},
	{Texts: 0},
	{BoardSettings: 0},
	{carLogo: 0},
	{btnCloseSettings: 0},
	{btnFullscreen: 0},
	{btnLanguage: 0},
	{btnSound: 0},
	{LocalStorage: 0},
	{background: 0},
	{btnHome: 0},
	{CounterDiamond: 0},
	{ShopSlider: 0},
	{boardCars: 0},
	{btnLeft: 0},
	{btnRight: 0},
	{btnSave: 0},
	{boardSpeed: 0},
	{Num: 0},
	{SpeedLogo: 0},
	{Index: 0},
	{Car1: 0},
	{Car2: 0},
	{Car3: 0},
	{price: 0},
	{btnBuyCar: 0},
	{boardColor: 0},
	{id: 0},
	{Car: 0},
	{btnColor0: 0},
	{btnColor1: 0},
	{btnColor2: 0},
	{btnColor3: 0},
	{btnColor4: 0},
	{btnColor5: 0},
	{btnColor6: 0},
	{btnOverContinue: 0},
	{btnOverHome: 0},
	{PauseBoard: 0},
	{bgWin: 0},
	{boardWin: 0},
	{btnboardHome: 0},
	{btnboardRetry: 0},
	{Star: 0},
	{TiledBackground: 0},
	{boardCounter: 0},
	{btnPause: 0},
	{Physics: 0},
	{PoliceCar: 0},
	{Lightpolice: 0},
	{Sine2: 0},
	{RotatePoliceCar: 0},
	{Sprite: 0},
	{DefCars: 0},
	{diamond: 0},
	{Pin: 0},
	{carSmoke: 0},
	{ChainsawParticles: 0},
	{Fade: 0},
	{rubber: 0},
	{Sprite2: 0},
	{Nitro: 0},
	{BufDown: 0},
	{BufSpeed: 0},
	{DownRound: 0},
	{SpeedRound: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{AJAX: 0},
	{Language: 0},
	{CarUnlock: 0},
	{ColorsUnlock: 0},
	{Cars: 0},
	{Colors: 0},
	{Sound: 0},
	{LoadGame: 0},
	{Score: 0},
	{BestScore: 0},
	{SelectCar: 0},
	{Diamond: 0},
	{ColorCar1: 0},
	{ColorCar2: 0},
	{ColorCar3: 0},
	{LastScore: 0},
	{Variable1: 0},
	{Action: 0},
	{GameSpeed: 0},
	{Avail: 0},
	{STX: 0},
	{ETX: 0},
	{STY: 0},
	{ETY: 0},
	{GameScore: 0},
	{Velocity: 0},
	{XEqual: 0},
	{YEqual: 0}
];

self.InstanceType = {
	BackgroundMenu: class extends self.ITiledBackgroundInstance {},
	WhiteBoard: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	btnShop: class extends self.ISpriteInstance {},
	Counters: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Texts: class extends self.ITextInstance {},
	BoardSettings: class extends self.ISpriteInstance {},
	carLogo: class extends self.ISpriteInstance {},
	btnCloseSettings: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	background: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	CounterDiamond: class extends self.ISpriteInstance {},
	ShopSlider: class extends self.ISpriteInstance {},
	boardCars: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnSave: class extends self.ISpriteInstance {},
	boardSpeed: class extends self.ISpriteInstance {},
	SpeedLogo: class extends self.ISpriteInstance {},
	Car1: class extends self.ISpriteInstance {},
	Car2: class extends self.ISpriteInstance {},
	Car3: class extends self.ISpriteInstance {},
	btnBuyCar: class extends self.ISpriteInstance {},
	boardColor: class extends self.ISpriteInstance {},
	btnColor0: class extends self.ISpriteInstance {},
	btnColor1: class extends self.ISpriteInstance {},
	btnColor2: class extends self.ISpriteInstance {},
	btnColor3: class extends self.ISpriteInstance {},
	btnColor4: class extends self.ISpriteInstance {},
	btnColor5: class extends self.ISpriteInstance {},
	btnColor6: class extends self.ISpriteInstance {},
	btnOverContinue: class extends self.ISpriteInstance {},
	btnOverHome: class extends self.ISpriteInstance {},
	PauseBoard: class extends self.ISpriteInstance {},
	bgWin: class extends self.ISpriteInstance {},
	boardWin: class extends self.ISpriteInstance {},
	btnboardHome: class extends self.ISpriteInstance {},
	btnboardRetry: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	boardCounter: class extends self.ISpriteInstance {},
	btnPause: class extends self.ISpriteInstance {},
	PoliceCar: class extends self.ISpriteInstance {},
	Lightpolice: class extends self.ISpriteInstance {},
	RotatePoliceCar: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	DefCars: class extends self.ISpriteInstance {},
	diamond: class extends self.ISpriteInstance {},
	carSmoke: class extends self.IParticlesInstance {},
	ChainsawParticles: class extends self.IParticlesInstance {},
	rubber: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Nitro: class extends self.ISpriteInstance {},
	BufDown: class extends self.ISpriteInstance {},
	BufSpeed: class extends self.ISpriteInstance {},
	DownRound: class extends self.ISpriteInstance {},
	SpeedRound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Language: class extends self.IArrayInstance {},
	CarUnlock: class extends self.IArrayInstance {},
	ColorsUnlock: class extends self.IArrayInstance {},
	Cars: class extends self.ISpriteInstance {},
	Colors: class extends self.ISpriteInstance {}
}